// import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

import type { Metadata } from 'next';

import AuthProvider from '../components/provider/AuthProvider';
import { ToastContainer } from 'react-toastify';
import ThemeProvider from '../components/provider/ThemeProvider';
import { cn } from '@/lib/utils';
import { ModalProvider } from '../components/provider/ModalProvider';

// export const fontSans = FontSans({
//   subsets: ['latin'],
//   variable: '--font-sans'
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <body className={cn('bg-white dark:bg-[#313338] font-sans font-medium')}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            storageKey="chatapp-theme"
          >
            {children}
            <ToastContainer />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
